# These are supported funding model platforms

github:  [wenwoha, gingernet, chaineye]
patreon: gingernet
open_collective: gingernet
ko_fi: gingernet
tidelift: gingernet
community_bridge: gingernet
liberapay: gingernet
issuehunt: gingernet
otechie: gingernet
lfx_crowdfunding:  cloud-gingernet
custom: ['https://www.wenwoha.com/', 'https://chaineye.info/', 'https://gingernet.vip/']
